# Generated by Django 5.0.7 on 2024-07-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', unique=True)),
            ],
            options={
                'verbose_name': 'MenuItem',
                'verbose_name_plural': 'MenuItems',
                'db_table': 'menu_items',
                'ordering': ['order'],
            },
        ),
    ]
