# Generated by Django 5.0.7 on 2024-07-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuitem_menu_alter_menuitem_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='menu',
            new_name='menus',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.menuitem'),
        ),
    ]
